runtime: nodejs22
env: standard

instance_class: F1
automatic_scaling:
  max_instances: 2

entrypoint: node -e ""

handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html
  expiration: 1s
- url: /(.*)
  static_files: build/\1
  upload: build/(.*)
